### ISSUE TITLE
Add Terminal for Hacker Product

### ISSUE THREAD

**Issue by apophis51** [apophis51/next-js-Portfolio#72]
We need to get our Hacker terminal Up online

**Comment by apophis51** [comment]
Our code works fine but results in errors in deployment
```javascript
'use client'
import React, { useEffect, useRef } from 'react';
import { Terminal } from 'xterm';
import 'xterm/css/xterm.css';

export default function TerminalComponent() {
  const terminalRef = useRef(null);

  const handleEnterKeyPress = (userInput) => {
    console.log('User input:', userInput.trim());
    // Add your custom logic here based on the user input
  };

  useEffect(() => {
    const terminal = new Terminal({
      cursorBlink: true,
    });

    terminal.open(terminalRef.current);
    terminal.focus();

    let userInput = '';

    terminal.onData((data) => {
      // Capture user input
      userInput += data;

      // Write the data to the terminal
      terminal.write(data);

      // Check for Enter key (ASCII code 13)
      if (data.charCodeAt(0) === 13) {
        // Handle Enter key
        handleEnterKeyPress(userInput);

        // Clear user input
        userInput = '';

        // Move to a new line in the terminal
        terminal.writeln('');
      }
    });

    return () => {
      terminal.dispose();
    };
  }, []);

  return <div ref={terminalRef} />;
}
```

we get these errors: 

<html>
<body>

ReferenceError: self is not defined
--
00:35:49.056 | at 68329 (/vercel/path0/.next/server/chunks/3510.js:1:299)
00:35:49.057 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:161)
00:35:49.057 | at 91477 (/vercel/path0/.next/server/app/(main site)/(Landing Pages)/FiringRange/page.js:1:2204)
00:35:49.057 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:161)
00:35:49.057 | at N (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:59:5712)
00:35:49.057 | at $ (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:59:4391)
00:35:49.057 | at rC (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:29810)
00:35:49.058 | at nO (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:56417)
00:35:49.058 | at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)
00:35:49.058 | at nA (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:61017)
00:35:49.722 |  
00:35:49.723 | Error occurred prerendering page "/FiringRange". Read more: https://nextjs.org/docs/messages/prerender-error
00:35:49.723 | ReferenceError: self is not defined
00:35:49.723 | at 68329 (/vercel/path0/.next/server/chunks/3510.js:1:299)
00:35:49.723 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:161)
00:35:49.723 | at 91477 (/vercel/path0/.next/server/app/(main site)/(Landing Pages)/FiringRange/page.js:1:2204)
00:35:49.724 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:161)
00:35:49.724 | at N (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:59:5712)
00:35:49.724 | at $ (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:59:4391)
00:35:49.724 | at rC (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:29810)
00:35:49.724 | at nO (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:56417)
00:35:49.724 | at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)
00:35:49.725 | at nA (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:61017)
00:35:51.376 | Generating static pages (14/28)
00:35:54.578 | Generating static pages (21/28)


</body>
</html>

so we are going to push revert the change for now

**Comment by apophis51** [comment]
New deployment successful with our component commented out. Lets just try to implement the backend work first by http methods first... then we can try expirmenting with sockets next.... lets just get the terminal output working correctly then retry the xterm library integration

**Comment by apophis51** [comment]
The error was related to server side rendering. We referenced https://nextjs.org/docs/app/building-your-application/rendering/server-components and learned that we can deopt from serverside rendering by using a dynamic function from their list ... that would deopt our code from ssr. 

`import Container from '@mui/material/Container';
import Hero from '../../Components/Hero'
import TerminalComponent from './TerminalComponent.js';
import TerminalShell from './TerminalShell.js'

import { headers } from 'next/headers'



export default function FiringRange() {
  const headersList = headers()
  const referer = headersList.get('referer')

  return (
    <Container maxWidth="xl"  >
        <Hero contentNeeded = {"Hacker Firing Range"}/>
        <TerminalComponent />
        {/* <div>Referer: {referer}</div> */}
        {/* <TerminalShell /> */}
    </Container>
  )
}
`

we imported headers and use it as a fluff just to trigger no ssr and it worked!

**Comment by apophis51** [comment]
we updated the code base to use dynamic rendering explicitly

```javascript
import Container from '@mui/material/Container';
import Hero from '../../Components/Hero'
import dynamic from 'next/dynamic'

const App = dynamic(() => import('./App.js'), { ssr: false })



export default function FiringRange() {
  return (
    <Container maxWidth="xl"  >
        <Hero contentNeeded = {"Hacker Firing Range"}/>
        <App />
    </Container>
  )
}
```

this will also be blogged in our "How to Disable NextJs from pre-Rendering a page"  blog on malcmind
